### ISSUE TITLE
Request timeout prints bot key to output

### ISSUE THREAD

**Issue by mtrp12** [AardCrowley/Telegram#2]
![image](https://user-images.githubusercontent.com/6695345/131429638-44db711c-6455-439e-8d4d-bdb95fb57cb8.png)

I am not sure if plugin output gets logged, but if it gets logged, requesting to no print bot key to output.

**Comment by AardCrowley** [comment]
Plugin output does not get logged unless you specifically tell it to,
though I'll state too that if it did, I would not be able to disable it
without completely modifying Fiendish's async code. In any case, shouldn't
be anything to worry about.
